package com.gentux.datos.template;

import com.gentux.datos.dto.*;
import com.gentux.datos.util.*;

public class ClaseBaseDatosTuxedoTemplate
{
  protected static String nl;
  public static synchronized ClaseBaseDatosTuxedoTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    ClaseBaseDatosTuxedoTemplate result = new ClaseBaseDatosTuxedoTemplate();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "";
  protected final String TEXT_2 = NL + "long ";
  protected final String TEXT_3 = "Insertar";
  protected final String TEXT_4 = "(";
  protected final String TEXT_5 = " ";
  protected final String TEXT_6 = ", char *mensaje)" + NL + "{" + NL + "   EXEC SQL BEGIN DECLARE SECTION;";
  protected final String TEXT_7 = NL + "     ";
  protected final String TEXT_8 = " db";
  protected final String TEXT_9 = ";" + NL + "   EXEC SQL END DECLARE SECTION;" + NL + "" + NL + "   db";
  protected final String TEXT_10 = " = ";
  protected final String TEXT_11 = ";" + NL + "" + NL + "   " + NL + "   EXEC SQL SELECT" + NL + "      SECUENCIA_";
  protected final String TEXT_12 = ".NEXTVAL" + NL + "   INTO ";
  protected final String TEXT_13 = NL + "      ";
  protected final String TEXT_14 = NL + "   FROM DUAL;" + NL + "   " + NL + "   " + NL + "   if (sqlca.sqlcode != DBA_SUCCESS){" + NL + "      strcpy(mensaje, sqlca.sqlerrm.sqlerrmc); " + NL + "      return (ErrorSql(sqlca));" + NL + "   }" + NL + "       " + NL + "   " + NL + "      EXEC SQL INSERT INTO ";
  protected final String TEXT_15 = " (";
  protected final String TEXT_16 = NL;
  protected final String TEXT_17 = NL + "   )" + NL + "   VALUES (" + NL + "  ";
  protected final String TEXT_18 = NL + "       " + NL + "      );" + NL + "" + NL + "   if (sqlca.sqlcode != DBA_SUCCESS) {" + NL + "      strcpy(mensaje, sqlca.sqlerrm.sqlerrmc);" + NL + "      return ErrorSql(sqlca);" + NL + "   }" + NL + "   " + NL + "   return SQL_SUCCESS;" + NL + "}" + NL + "" + NL + " " + NL + "long ";
  protected final String TEXT_19 = "Modificar";
  protected final String TEXT_20 = ", char *mensaje)" + NL + "{" + NL + "  EXEC SQL BEGIN DECLARE SECTION;";
  protected final String TEXT_21 = ";" + NL + " " + NL + " " + NL + "   EXEC SQL UPDATE ";
  protected final String TEXT_22 = "  SET";
  protected final String TEXT_23 = NL + "   WHERE";
  protected final String TEXT_24 = NL + "    ;" + NL + " " + NL + "   if (sqlca.sqlcode != DBA_SUCCESS) {" + NL + "      strcpy(mensaje, sqlca.sqlerrm.sqlerrmc);" + NL + "      return ErrorSql(sqlca);" + NL + "   }" + NL + " " + NL + "   return SQL_SUCCESS;" + NL + "}" + NL + " " + NL + "long ";
  protected final String TEXT_25 = "Eliminar";
  protected final String TEXT_26 = ", char *mensaje)" + NL + "{" + NL + "EXEC SQL BEGIN DECLARE SECTION;";
  protected final String TEXT_27 = ";" + NL + " " + NL + "   EXEC SQL DELETE FROM ";
  protected final String TEXT_28 = NL + "      WHERE ";
  protected final String TEXT_29 = NL + "      ;" + NL + " " + NL + "   if (sqlca.sqlcode != DBA_SUCCESS) {" + NL + "      strcpy(mensaje, sqlca.sqlerrm.sqlerrmc); " + NL + "      return ErrorSql(sqlca);" + NL + "   }   " + NL + "   " + NL + "   return SQL_SUCCESS;" + NL + "" + NL + "} " + NL + "" + NL + "long ";
  protected final String TEXT_30 = "Buscar";
  protected final String TEXT_31 = ", ";
  protected final String TEXT_32 = " *";
  protected final String TEXT_33 = " *db";
  protected final String TEXT_34 = ";" + NL + "      long dbCodigo;" + NL + "   EXEC SQL END DECLARE SECTION;" + NL + " " + NL + "   db";
  protected final String TEXT_35 = ";" + NL + "   dbCodigo = codigo;   " + NL + " " + NL + "   EXEC SQL SELECT";
  protected final String TEXT_36 = NL + "   INTO";
  protected final String TEXT_37 = NL + "   FROM  ";
  protected final String TEXT_38 = NL + "   WHERE ";
  protected final String TEXT_39 = NL + "   ";
  protected final String TEXT_40 = NL + "   ;   " + NL + " " + NL + "   if (sqlca.sqlcode != DBA_SUCCESS) {" + NL + "      strcpy(mensaje, sqlca.sqlerrm.sqlerrmc);" + NL + "      return ErrorSql(sqlca);" + NL + "   }" + NL + "   " + NL + "   return SQL_SUCCESS;" + NL + "" + NL + "}  " + NL + "" + NL + "  " + NL + "long ";
  protected final String TEXT_41 = "BuscarTodos";
  protected final String TEXT_42 = "(Q_HANDLE *lista, char *mensaje)" + NL + "{" + NL + "   long estadoFetch;" + NL + "   EXEC SQL BEGIN DECLARE SECTION;";
  protected final String TEXT_43 = ";" + NL + "   EXEC SQL END DECLARE SECTION;" + NL + "" + NL + "   lista->itemLen = sizeof(";
  protected final String TEXT_44 = ");" + NL + "" + NL + "   EXEC SQL DECLARE Cursor";
  protected final String TEXT_45 = " CURSOR FOR" + NL + "   SELECT";
  protected final String TEXT_46 = "  ;" + NL + "" + NL + "   EXEC SQL OPEN Cursor";
  protected final String TEXT_47 = ";" + NL + "   if (sqlca.sqlcode != DBA_SUCCESS) {" + NL + "     strcpy(mensaje, sqlca.sqlerrm.sqlerrmc);" + NL + "     return ErrorSql(sqlca);" + NL + "   }    " + NL + "" + NL + "   while (sqlca.sqlcode == DBA_SUCCESS)" + NL + "   {" + NL + "      if ((db";
  protected final String TEXT_48 = " = (";
  protected final String TEXT_49 = " *)QMakeItem(lista)) == NULL)" + NL + "      {" + NL + "         EXEC SQL CLOSE Cursor";
  protected final String TEXT_50 = ";" + NL + "         return SQL_MEMORY;" + NL + "      }" + NL + "" + NL + "      EXEC SQL FETCH Cursor";
  protected final String TEXT_51 = " INTO";
  protected final String TEXT_52 = NL + "        ";
  protected final String TEXT_53 = NL + "      ;" + NL + "      " + NL + "     if (sqlca.sqlcode != DBA_SUCCESS)" + NL + "      {" + NL + "         strcpy(mensaje, sqlca.sqlerrm.sqlerrmc);" + NL + "         QRemoveItem(lista, lista->count - 1);" + NL + "         if (sqlca.sqlcode != DBA_NOT_FOUND)" + NL + "            estadoFetch = ErrorSql(sqlca);" + NL + "         else if (lista->count)" + NL + "            estadoFetch = SQL_SUCCESS;" + NL + "         else" + NL + "            estadoFetch = SQL_NOT_FOUND;" + NL + "         EXEC SQL CLOSE Cursor";
  protected final String TEXT_54 = ";" + NL + "         return estadoFetch;" + NL + "      }" + NL + "   }" + NL + "   " + NL + "   return SQL_SUCCESS;" + NL + "}";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    stringBuffer.append(TEXT_1);
     Table table = (Table) argument; 
    stringBuffer.append(TEXT_2);
    stringBuffer.append( GeneradorUtil.getPrefijoServicioDatos());
    stringBuffer.append(TEXT_3);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_4);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_5);
    stringBuffer.append(table.getName());
    stringBuffer.append(TEXT_6);
    stringBuffer.append(TEXT_7);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_8);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_9);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_10);
    stringBuffer.append(table.getName());
    stringBuffer.append(TEXT_11);
    stringBuffer.append(table.getTable_name());
    stringBuffer.append(TEXT_12);
    stringBuffer.append(TEXT_13);
    stringBuffer.append( GeneradorUtil.getDBVariables(table.getNameWithFirstLetterUpperCase(),".",table.getColumnasDeClaveUnicaPrincipal()));
    stringBuffer.append(TEXT_14);
    stringBuffer.append(table.getTable_name());
    stringBuffer.append(TEXT_15);
    stringBuffer.append(TEXT_16);
    stringBuffer.append( GeneradorUtil.getFields(table.getColumnas()));
    stringBuffer.append(TEXT_17);
    stringBuffer.append(TEXT_16);
    stringBuffer.append( GeneradorUtil.getDBVariables(table.getNameWithFirstLetterUpperCase(),".",table.getColumnas()));
    stringBuffer.append(TEXT_18);
    stringBuffer.append( GeneradorUtil.getPrefijoServicioDatos());
    stringBuffer.append(TEXT_19);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_4);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_5);
    stringBuffer.append(table.getName());
    stringBuffer.append(TEXT_20);
    stringBuffer.append(TEXT_13);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_8);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_9);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_10);
    stringBuffer.append(table.getName());
    stringBuffer.append(TEXT_21);
    stringBuffer.append(table.getTable_name());
    stringBuffer.append(TEXT_22);
    stringBuffer.append(TEXT_16);
    stringBuffer.append( GeneradorUtil.asignarVariablesHaciaColumnasEnSet(table.getNameWithFirstLetterUpperCase(), table.getColumnasNoPertenecenAClaveUnica() ) );
    stringBuffer.append(TEXT_23);
    stringBuffer.append(TEXT_16);
    stringBuffer.append( GeneradorUtil.asignarVariablesHaciaColumnasEnWhere(table.getNameWithFirstLetterUpperCase(), GeneradorUtil.ES_CON_REGISTRO, table.getColumnasDeClaveUnicaPrincipal() ) );
    stringBuffer.append(TEXT_24);
    stringBuffer.append( GeneradorUtil.getPrefijoServicioDatos());
    stringBuffer.append(TEXT_25);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_4);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_5);
    stringBuffer.append(table.getName());
    stringBuffer.append(TEXT_26);
    stringBuffer.append(TEXT_13);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_8);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_9);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_10);
    stringBuffer.append(table.getName());
    stringBuffer.append(TEXT_27);
    stringBuffer.append(table.getTable_name());
    stringBuffer.append(TEXT_28);
    stringBuffer.append(TEXT_16);
    stringBuffer.append( GeneradorUtil.asignarVariablesHaciaColumnasEnWhere(table.getNameWithFirstLetterUpperCase(), GeneradorUtil.ES_CON_REGISTRO, table.getColumnasDeClaveUnicaPrincipal() ) );
    stringBuffer.append(TEXT_29);
    stringBuffer.append( GeneradorUtil.getPrefijoServicioDatos());
    stringBuffer.append(TEXT_30);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_4);
    stringBuffer.append(GeneradorUtil.drawDefinitionVariables(table.getColumnasDeClaveUnicaPrincipal()) );
    stringBuffer.append(TEXT_31);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_32);
    stringBuffer.append(table.getName());
    stringBuffer.append(TEXT_6);
    stringBuffer.append(TEXT_13);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_33);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_34);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_10);
    stringBuffer.append(table.getName());
    stringBuffer.append(TEXT_35);
    stringBuffer.append(TEXT_16);
    stringBuffer.append( GeneradorUtil.getFields(table.getColumnas()));
    stringBuffer.append(TEXT_36);
    stringBuffer.append(TEXT_16);
    stringBuffer.append( GeneradorUtil.getDBVariables(table.getNameWithFirstLetterUpperCase(),"->",table.getColumnas()));
    stringBuffer.append(TEXT_37);
    stringBuffer.append(table.getTable_name());
    stringBuffer.append(TEXT_38);
    stringBuffer.append(TEXT_39);
    stringBuffer.append( GeneradorUtil.asignarVariablesHaciaColumnasEnWhere(table.getNameWithFirstLetterUpperCase(), !GeneradorUtil.ES_CON_REGISTRO , table.getColumnasDeClaveUnicaPrincipal() ) );
    stringBuffer.append(TEXT_40);
    stringBuffer.append( GeneradorUtil.getPrefijoServicioDatos());
    stringBuffer.append(TEXT_41);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_42);
    stringBuffer.append(TEXT_13);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_33);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_43);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_44);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_45);
    stringBuffer.append(TEXT_7);
    stringBuffer.append( GeneradorUtil.getFields(table.getColumnas()));
    stringBuffer.append(TEXT_37);
    stringBuffer.append(table.getTable_name());
    stringBuffer.append(TEXT_46);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_47);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_48);
    stringBuffer.append( GeneradorUtil.getNombreTipoEstructura(table.getName()));
    stringBuffer.append(TEXT_49);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_50);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_51);
    stringBuffer.append(TEXT_52);
    stringBuffer.append( GeneradorUtil.getDBVariables(table.getNameWithFirstLetterUpperCase(),"->",table.getColumnas()));
    stringBuffer.append(TEXT_53);
    stringBuffer.append(table.getNameWithFirstLetterUpperCase());
    stringBuffer.append(TEXT_54);
    stringBuffer.append(TEXT_16);
    return stringBuffer.toString();
  }
}
